### ISSUE TITLE
Recover from temporary disconnections from database server

### ISSUE THREAD

**Issue by drmalex07** [OpertusMundi/catalogue-service#12]
It is possible that the database server (either the real one or a connection pooler in front of it) will οccasionally disconnect some connections (e.g. because they are idle, or because the server refreshes its own pool processes).

The application should be able to recover from such an event by cleaning up the old (closed) connection and establishing a new connection (trying with some backoff interval of 1s, 2s, 4s ...).

**Comment by kalxas** [comment]
Please have a look here, possibly related:
https://github.com/geopython/pycsw/pull/696
https://github.com/geopython/pycsw/pull/685

**Comment by nleond** [comment]
Fixed for now
